name: benchmark_prop_vs_func
version: 0.0.1
authors:
- Chirayu Krishnappa <chirayu@chirayuk.com>
description: benchmark_prop_vs_func
homepage: https://github.com/chirayuk/sample
environment:
  sdk: '>=1.4.0'
dependencies:
  angular:
    git:
      url: git://github.com/chirayuk/angular.dart
      ref: 20140624-stats-g3v1x
      # url: /Users/chirayu/ck/vcs/angular.dart
  di: '>=1.0.0 <2.0.0'

transformers:
- angular
